inputs=[1:6]'
outputs=[1 2]'
net=network(...
1,...
2,...
[1;0],...
[1;0],...
[0 0;1 0],...
[0 1]...
);
view(net);
net.layers{1}.size=5;
net.layers{1}.transferFcn='logsig';
view(net);
net=configure(net,inputs,outputs);
view(net);
initial_output=net(inputs);
net.trainFcn='trainlm';
net.performFcn='mse';
net=train(net,inputs,outputs);
final_output=net(inputs)